### PR TITLE
Addressing None of the above

### PR DESCRIPTION
**Pull request by saulakravitz**
New Observations:
  - ObservationUnknownFinalRouteMethodDelivery (complements ProcedureFinalRouteMethodDelivery)
  - ObservationNoneOfSpecifiedInfectionsPresentDuringPregnancy (complements ConditionInfectionPresentDuringPregnancy)
  - ObservationNoneOfSpecifiedCongenitalAnomoliesOfTheNewborn (complements ConditionCongenitalAnomalyOfNewborn)  
  - ObservationNOneOfSpecifiedObstetricsProcedures (complements Obstetric Procedures) 
  
  ValueSets:
    - Valueset for DeliveryRoutes:  changed a code to a procedure code, and removed Unknown since it is now covered by the ObservationUnknownFinalRouteMethodDelivery.
    - ValueSet Obstetric Procedure:  used to contain one procedure code, and "None".   The None was inappropriate. 
    - ValueSetObstetricProcedureOutcome was added, since only two of the 3 values from the standard procedure outcome valueset are allowed.
  
  SNOMED Code Replacements:
    - Code for Normal delivery changed from a (finding) code to a (procedure) code
    - Code for NICU admission changed from an (environment) code to a (procedure) code.
    
 All bundles, compositions, and examples updated.
 Need to add examples for all of the NOneOf Observations.
 
 Added some change log content, but probably more needed.
 
 Spreadsheets and generated content need to be updated to reflect these changes.

### CODE REVIEW

**Review by ptran265 — APPROVED** [review]
pushed up a few typo fixes

**Comment by rpassas** [comment]
Should fetal presentations have an 'unknown' observation like final route and method of delivery?

**Comment by ptran265** [comment]
is it just me or am I not seeing the new ObservationNoneOfSpecifiedObstetricsProcedures?

**Comment by saulakravitz** [comment]
> fetal presentations

Try now...oops

**Comment by saulakravitz** [comment]
> Should fetal presentations have an 'unknown' observation like final route and method of delivery?

FinalRouteMethod is a PROCEDURE. So you can't have a procedure with a code of 'Unknown'.   So, we create a complementary observation. 

Presentation is an Observation with a proper LOINC code, and a value.  One of the values is Unknown.  So it is OK.

**Review by rpassas — APPROVED** [review]

**Pull request merged**
