### PR TITLE
remove VRCL and BFDR

### PR DESCRIPTION
**Pull request by ptran265**
- deleted VRCL and BFDR content, changed dependencies in sushi-config
- builds with Errors: 9, Warnings: 42, Info: 24, Broken Links: 1004

### CODE REVIEW

**Comment by rpassas** [comment]
We should remove the BFDR/VRCL page content just to clear up the QA report

**Comment by rpassas** [comment]
valueset-edit-bypass-01234-vr is in VRDR in the sandbox but is in VRCL since it was initially separated. We should probably make this change here in a follow up PR to keep VRDR up to date.

**Comment by saulakravitz** [comment]
@ptran265 -- do you want to take care of these now, or is there more pressing business?

**Comment by ptran265** [comment]
@saulakravitz I can work on it today

**Review by saulakravitz — APPROVED** [review]
@ptran265 if you can quickly take care of @rpassas suggestions now, great.
If you prefer to defer, just create a new ticket to followup.

**Review by saulakravitz — APPROVED** [review]

**Pull request merged**
